return {
		Accent = Color3.fromRGB(0, 255, 0),
		
		AcrylicMain = Color3.fromRGB(0, 0, 0),
		AcrylicBorder = Color3.fromRGB(50, 0, 100),
		AcrylicGradient = ColorSequence.new(Color3.fromRGB(20, 20, 20), Color3.fromRGB(0, 0, 0)),
		
		TitleBarLine = Color3.fromRGB(255, 0, 255),
		Tab = Color3.fromRGB(100, 0, 255),
		
		Element = Color3.fromRGB(28, 28, 28),
		ElementBorder = Color3.fromRGB(80, 80, 80),
		InElementBorder = Color3.fromRGB(100, 100, 100),
		ElementTransparency = 0.85,
		
		ToggleSlider = Color3.fromRGB(0, 255, 0),
		ToggleCorner = Color3.fromRGB(96, 96, 99),
		ToggleToggled = Color3.fromRGB(0, 0, 0),
		
		SliderRail = Color3.fromRGB(80, 0, 160),
		
		DropdownFrame = Color3.fromRGB(50, 50, 50),
		DropdownHolder = Color3.fromRGB(30, 30, 30),
		DropdownBorder = Color3.fromRGB(60, 60, 60),
		DropdownOption = Color3.fromRGB(0, 255, 0),
		
		Keybind = Color3.fromRGB(0, 255, 0),
		
		Input = Color3.fromRGB(40, 40, 40),
		InputFocused = Color3.fromRGB(0, 0, 0),
		InputIndicator = Color3.fromRGB(80, 80, 80),
		InputIndicatorFocus = Color3.fromRGB(80, 80, 80),
		
		Dialog = Color3.fromRGB(20, 20, 20),
		DialogHolder = Color3.fromRGB(40, 0, 40),
		DialogHolderLine = Color3.fromRGB(80, 0, 160),
		DialogButton = Color3.fromRGB(30, 30, 30),
		DialogButtonBorder = Color3.fromRGB(0, 255, 0),
		DialogBorder = Color3.fromRGB(80, 0, 160),
		DialogInput = Color3.fromRGB(30, 30, 30),
		DialogInputLine = Color3.fromRGB(0, 255, 0),
		
		Text = Color3.fromRGB(255, 255, 255),
		SubText = Color3.fromRGB(200, 200, 200),
		Hover = Color3.fromRGB(100, 0, 255),
		HoverChange = 0.1,
	}
